// Regenerate all data/*-snapshot.js files from the live Postgres database.
// Run locally with: npm run refresh-data
// Requires DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD in .env.local (see .env.example).
// This script is NOT run on Vercel — the dashboard reads the committed snapshot files only.

import { Client } from "pg";
import { writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, "..", "data");
const SENT_LABEL = { positive: "positif", negative: "negatif", neutral: "netral" };

async function loadEnvLocal() {
  try {
    const raw = await readFile(path.join(__dirname, "..", ".env.local"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  } catch {
    // .env.local optional
  }
}

function fmtWeek(date) {
  const months = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"];
  return `${date.getDate()} ${months[date.getMonth()]}`;
}

function cap(s) {
  return s ? s[0].toUpperCase() + s.slice(1) : s;
}

async function writeSnapshot(filename, exports) {
  const body = Object.entries(exports)
    .map(([name, value]) => `export const ${name} = ${JSON.stringify(value, null, 2)};`)
    .join("\n\n");
  const content = `// Auto-generated by scripts/export-data.mjs — jangan edit manual.\n// Jalankan \`npm run refresh-data\` untuk regenerate.\n\n${body}\n`;
  await writeFile(path.join(DATA_DIR, filename), content, "utf8");
  console.log(`Wrote data/${filename}`);
}

async function exportSubject(client, subjectId) {
  const classified = await client.query(
    `SELECT count(*) n_total,
       count(*) FILTER (WHERE sentiment_label='positive') pos,
       count(*) FILTER (WHERE sentiment_label='negative') neg,
       count(*) FILTER (WHERE sentiment_label='neutral') neu
     FROM l1_silver.mention WHERE subject_id=$1 AND attribution_layer IS NOT NULL`,
    [subjectId]
  );
  const raw = await client.query(`SELECT count(*) n FROM l1_silver.mention WHERE subject_id=$1`, [subjectId]);
  const platform = await client.query(
    `SELECT platform, count(*) n,
       count(*) FILTER (WHERE sentiment_label='positive') pos,
       count(*) FILTER (WHERE sentiment_label='negative') neg,
       count(*) FILTER (WHERE sentiment_label='neutral') neu
     FROM l1_silver.mention WHERE subject_id=$1 AND attribution_layer IS NOT NULL
     GROUP BY 1 ORDER BY 2 DESC`,
    [subjectId]
  );
  const weekly = await client.query(
    `SELECT date_trunc('week', mention_date)::date wk, SUM(n_total) t, SUM(n_positive) p, SUM(n_negative) neg, SUM(n_neutral) neu
     FROM l2_gold.agg_sentiment_daily WHERE subject_id=$1 GROUP BY 1 ORDER BY 1`,
    [subjectId]
  );
  const topicMap = await client.query(
    `SELECT topic_id, category_label, SUM(n_total) n_total,
       ROUND(SUM(n_positive - n_negative)::numeric / NULLIF(SUM(n_total),0) * 100, 1) net
     FROM l2_gold.agg_topic_map WHERE subject_id=$1
     GROUP BY 1,2 ORDER BY n_total DESC LIMIT 10`,
    [subjectId]
  );
  const topContentRows = await client.query(
    `SELECT author_username, platform, LEFT(full_text,150) txt, like_count, sentiment_label
     FROM l1_silver.mention
     WHERE subject_id=$1 AND attribution_layer IN ('direct','institutional')
       AND (is_bot_suspected IS NOT TRUE) AND full_text IS NOT NULL AND full_text <> ''
     ORDER BY (COALESCE(like_count,0)+COALESCE(reply_count,0)+COALESCE(share_count,0)) DESC
     LIMIT 10`,
    [subjectId]
  );

  const ct = classified.rows[0];
  const netSentiment = ct.n_total > 0 ? (((ct.pos - ct.neg) / ct.n_total) * 100).toFixed(1) : "0.0";

  return {
    kpi: {
      relevantMentions: Number(ct.n_total),
      rawMentions: Number(raw.rows[0].n),
      positivePct: ct.n_total > 0 ? Math.round((ct.pos / ct.n_total) * 100) : 0,
      netSentiment: `${Number(netSentiment) >= 0 ? "+" : ""}${netSentiment}`,
    },
    platformData: platform.rows.map((r) => ({ platform: cap(r.platform), value: Number(r.n), pos: Number(r.pos), neg: Number(r.neg), neu: Number(r.neu) })),
    sentimentTrend: weekly.rows.map((r) => ({ week: fmtWeek(r.wk), positif: Number(r.p), netral: Number(r.neu), negatif: Number(r.neg) })),
    volumeTrend: weekly.rows.map((r) => ({ week: fmtWeek(r.wk), volume: Number(r.t) })),
    topTopicsVolume: topicMap.rows.map((r) => ({ topic: r.topic_id, category: r.category_label, n: Number(r.n_total), net: Number(r.net) })),
    topContent: topContentRows.rows.map((r) => ({
      handle: `@${r.author_username}`,
      platform: cap(r.platform),
      text: r.txt,
      sentiment: SENT_LABEL[r.sentiment_label] || "netral",
      likes: Number(r.like_count || 0),
    })),
  };
}

async function main() {
  await loadEnvLocal();

  const client = new Client({
    host: process.env.DB_HOST,
    port: Number(process.env.DB_PORT || 5432),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
  });
  await client.connect();

  // ---------- AJD (Self Perception) ----------
  const ajd = await exportSubject(client, "AJD");
  const attribution = await client.query(
    `SELECT
       count(*) FILTER (WHERE attribution_layer IS NULL) unclassified,
       count(*) FILTER (WHERE attribution_layer='institutional') institutional,
       count(*) FILTER (WHERE attribution_layer='attributed') attributed,
       count(*) FILTER (WHERE attribution_layer='direct') direct
     FROM l1_silver.mention WHERE subject_id='AJD'`
  );
  const at = attribution.rows[0];
  const audienceSegAjd = await client.query(`SELECT author_segment, n_total FROM l2_gold.agg_audience WHERE subject_id='AJD' ORDER BY n_total DESC`);
  const opportunityAjd = await client.query(
    `SELECT topic_id, category_label, avg_engagement_like FROM l2_gold.agg_opportunity_ajd ORDER BY avg_engagement_like DESC LIMIT 5`
  );
  const riskAjd = await client.query(
    `SELECT topic_id, category_label, n_negative_last_7d, n_negative_prior_7d, delta_7d, is_true_velocity, caveat FROM l2_gold.agg_risk_radar_ajd LIMIT 1`
  );

  await writeSnapshot("ajd-snapshot.js", {
    snapshotMeta: {
      subjectId: "AJD",
      subjectName: "Amri Jamaluddin",
      subjectTitle: "Bupati Kabupaten Kolaka",
      queryDate: new Date().toISOString().slice(0, 10),
      source: "kanalytics_spi_test (PostgreSQL) — l1_silver.mention / l2_gold.*",
    },
    kpi: ajd.kpi,
    attributionData: [
      { label: "Belum Terklasifikasi", value: Number(at.unclassified), note: "kandidat noise nama kembar" },
      { label: "Institusional", value: Number(at.institutional), note: "akun resmi Pemkab/media lokal" },
      { label: "Atribusi (Attributed)", value: Number(at.attributed), note: "disebut pihak ketiga" },
      { label: "Langsung (Direct)", value: Number(at.direct), note: "pernyataan resmi AJD" },
    ],
    platformData: ajd.platformData.map(({ platform, value }) => ({ platform, value })),
    audienceSegmentData: audienceSegAjd.rows.map((r) => ({ name: r.author_segment, value: Number(r.n_total) })),
    sentimentTrend: ajd.sentimentTrend,
    volumeTrend: ajd.volumeTrend,
    topicEngagement: opportunityAjd.rows.map((r) => ({ title: r.category_label, eng: Number(r.avg_engagement_like) })),
    topTopicsVolume: ajd.topTopicsVolume,
    riskRadar: riskAjd.rows[0]
      ? {
          topicLabel: riskAjd.rows[0].topic_id,
          categoryLabel: riskAjd.rows[0].category_label,
          nNegativeLast7d: Number(riskAjd.rows[0].n_negative_last_7d),
          nNegativePrior7d: Number(riskAjd.rows[0].n_negative_prior_7d),
          delta7d: Number(riskAjd.rows[0].delta_7d),
          isTrueVelocity: riskAjd.rows[0].is_true_velocity,
          caveat: riskAjd.rows[0].caveat,
        }
      : null,
    topContent: ajd.topContent,
  });

  // ---------- KLK (My Regency) ----------
  const klk = await exportSubject(client, "KLK");
  const opportunityKlk = await client.query(
    `SELECT topic_id, category_label, avg_engagement_like FROM l2_gold.agg_opportunity_klk
     WHERE topic_id <> 'uncategorized' ORDER BY avg_engagement_like DESC LIMIT 5`
  );
  const riskKlk = await client.query(
    `SELECT topic_id, category_label, n_negative_last_7d, n_negative_prior_7d, delta_7d
     FROM l2_gold.agg_risk_radar_klk ORDER BY delta_7d DESC`
  );

  await writeSnapshot("klk-snapshot.js", {
    snapshotMeta: {
      subjectId: "KLK",
      subjectName: "Kabupaten Kolaka",
      queryDate: new Date().toISOString().slice(0, 10),
      source: "kanalytics_spi_test (PostgreSQL) — l1_silver.mention / l2_gold.*",
    },
    kpi: klk.kpi,
    platformData: klk.platformData,
    sentimentTrend: klk.sentimentTrend,
    volumeTrend: klk.volumeTrend,
    topicEngagement: opportunityKlk.rows.map((r) => ({ title: r.category_label, eng: Number(r.avg_engagement_like) })),
    topTopicsVolume: klk.topTopicsVolume,
    riskRadar: riskKlk.rows.map((r) => ({
      topic: r.topic_id,
      category: r.category_label,
      last7d: Number(r.n_negative_last_7d),
      prior7d: Number(r.n_negative_prior_7d),
      delta: Number(r.delta_7d),
    })),
    topContent: klk.topContent,
  });

  // ---------- Audience / Community (derived from AJD mentions) ----------
  const audienceSeg = await client.query(
    `SELECT author_segment, count(*) n, avg(author_followers) avg_followers
     FROM l1_silver.mention WHERE subject_id='AJD' AND attribution_layer IS NOT NULL AND author_segment IS NOT NULL
     GROUP BY 1 ORDER BY 2 DESC`
  );
  const emotion = await client.query(
    `SELECT emotion_label, count(*) n FROM l1_silver.mention
     WHERE subject_id='AJD' AND attribution_layer IS NOT NULL AND emotion_label IS NOT NULL
     GROUP BY 1 ORDER BY 2 DESC`
  );
  const botStats = await client.query(
    `SELECT count(*) FILTER (WHERE is_bot_suspected) bot_n FROM l1_silver.mention
     WHERE subject_id='AJD' AND attribution_layer IS NOT NULL`
  );
  const supporters = await client.query(
    `SELECT author_username, platform, author_followers, LEFT(full_text,140) txt, like_count
     FROM l1_silver.mention
     WHERE subject_id='AJD' AND attribution_layer IS NOT NULL
       AND author_segment='konsumen' AND emotion_label='dukungan'
     ORDER BY COALESCE(author_followers,0) DESC, COALESCE(like_count,0) DESC
     LIMIT 10`
  );
  const officials = await client.query(
    `SELECT author_username, platform, count(*) posts,
       sum(COALESCE(like_count,0)+COALESCE(reply_count,0)+COALESCE(share_count,0)) engagement
     FROM l1_silver.mention
     WHERE subject_id='AJD' AND attribution_layer IS NOT NULL
       AND author_segment='institusional' AND author_username IS NOT NULL
       AND author_username NOT IN ('amri_djamaluddin', 'amrijamaluddin_')
     GROUP BY 1,2 ORDER BY posts DESC LIMIT 5`
  );

  const totalSeg = audienceSeg.rows.reduce((s, r) => s + Number(r.n), 0);
  const topPlatform = ajd.platformData[0];

  await writeSnapshot("audience-snapshot.js", {
    snapshotMeta: {
      subjectId: "AJD",
      queryDate: new Date().toISOString().slice(0, 10),
      source: "kanalytics_spi_test (PostgreSQL) — l1_silver.mention (attribution_layer relevan)",
      missingFields: ["usia", "gender", "kota domisili"],
    },
    kpi: {
      communityCandidates: supporters.rowCount,
      segmentSplit: audienceSeg.rows.map((r) => `${Math.round((Number(r.n) / totalSeg) * 100)}% ${cap(r.author_segment)}`).join(" / "),
      topPlatformShare: topPlatform ? `${topPlatform.platform} ${Math.round((topPlatform.value / ajd.kpi.relevantMentions) * 100)}%` : "-",
      botDetected: Number(botStats.rows[0].bot_n),
    },
    segmentData: audienceSeg.rows.map((r) => ({ name: cap(r.author_segment), value: Number(r.n), avgFollowers: Math.round(Number(r.avg_followers || 0)) })),
    platformActivity: ajd.platformData.map(({ platform, value }) => ({ platform, value })),
    emotionData: emotion.rows.map((r) => ({ emotion: cap(r.emotion_label), value: Number(r.n) })),
    communitySupporters: supporters.rows.map((r) => ({
      handle: `@${r.author_username}`,
      platform: cap(r.platform),
      followers: r.author_followers,
      text: r.txt,
      likes: Number(r.like_count || 0),
    })),
    officialAccounts: officials.rows.map((r) => ({
      handle: `@${r.author_username}`,
      platform: cap(r.platform),
      posts: Number(r.posts),
      engagement: Number(r.engagement),
    })),
  });

  await client.end();
  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
